path: /mnt/d/Codes/ppe_yolov8/ppe_dataset #dataset absolute path

train: images/train
test: images/test
val: images/val

# classes
names:
  0: hard-hat
  1: gloves
  2: mask
  3: glasses
  4: boots
  5: vest
  6: ppe-suit
  7: ear-protector
  8: safety-harness